import Head from 'next/head'

import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Rush</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='he' >
       <img  src="../group-187.svg"  alt="" />   
     <img className='hed' src="../bo.png"     /> 
     <img src="../vecto12.svg"     /> 
     
     <button type="button" className=" hef btn ">Sign in</button>
     </div>    
         <hr className='hrc' />
     
     
          
          
          </>
  )
}
