import Head from 'next/head'


import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Rush</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header */}
      
      <div className='he ' >
       <img  src="../group-187.svg"  alt="" />   
     <img className='hed' src="../bo.png"     /> 
     <img src="../vecto12.svg"     /> 
     <div className='nm' >
     <button  type="button" className=" hef btn d-sm-none d-md-block d-none d-sm-block ">Sign in</button>
     </div>
     </div>    
         <hr className='hrc' />
       
       {/* end header */}

     {/* front image  */}
     <div className='cardhe'>
    <div className="outerArea card bg-dark text-white" >
        
        <div className=" innerArea coverimgback alicard " >
        <h5 className="heading card-title">Welcome to Russh!</h5>
                    
                    <div className="row">
                                    <div className="col-xl-6">
                                        <p className="txt card-text">
                                            Russh is a super platform that hosts and offers other platform as exclusive supcription
                                            services. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Atque excepturi
                                            reiciendis
                                            fugiat ut tempore corporis!
                                        </p>
                                    </div>
                                </div>
            
                                <div className="row">
                                    <div className="col-xl-6">
                                        <p className="txt card-text">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veniam,
                                            ullam?
                                            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolor, sunt.
                                        </p>
                                    </div>
                                </div>
                                <div className="row">
                                    <div className="col-xl-6">
                                        <p className="txt card-text">Ready to start? Enter your email to create and begin your
                                            membership.</p>
                                    </div>
                                </div>
                                <div className="row">
                                    <div className="col-xl-6  col-lg-6 col-md-6 col-sm-8">
                                        <form className="example" action="action_page.php">
                                            <input type="text" placeholder="Enter Your Email" name="search"/>
                                            <button type="submit">Send</button>
                                        </form>
                                    </div>
                                </div>
                                <div className="row">
                                    <div className="col-xl-6">
                                        <p className="txt card-text">Get the best platforms woth exclusive access all under one roof.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
            
       </div>




              {/* end of front image */}



                   {/* card 1*/}

<br />
<br />
<hr className='hrc' />
<br />

<div className="cardhe" >
<div className="row text-center">
                        <div className="col-md-6 cols">
       
            <h2 className="clo">Get exclusive access to
                the best platforms.</h2>
            <p className="clo">Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis quo, nisi, earum soluta aliquid rerum
                velit
                expedita excepturi fugit obcaecati aspernatur officiis temporibus suscipit nulla?</p>
        </div>
        <div className="col-md-6 cols">
            <img className="clim" src="../3e0731a1aebace26ecbebf02a63a6b19.png" alt=""/>
            </div></div>
        
   <p className='colio'>_</p>
  

    
<hr className='hrc' />
</div>
               {/* end of card 1 */}

            {/* card 2 */}

<div className="row text-center">
                        <div className="col-md-6 cols">
            <img className='climo' src="../qwe.png" alt=""/>
        </div>
        <div className="col-md-6 cols">
            <h2 className="clo">Subscribe to some of themost unique platforms.</h2>
            <p className="clo">Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis quo, nisi, earum soluta aliquid rerum
                velit
                expedita excepturi fugit obcaecati aspernatur officiis temporibus suscipit nulla?</p>
        </div>
        <p className='colio'>_</p>
  </div>

    
  <hr className='hrc' />
   
             {/* end of card 2 */}

            {/* card 3 */}

  <div className="cardhe" >
  <div className="row text-center">
                        <div className="col-md-6 cols">
            <h2 className="clo">Choose your favorite platforms subscribe.</h2>
            <p className="clo">Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis quo, nisi, earum soluta aliquid rerum
                velit
                expedita excepturi fugit obcaecati aspernatur officiis temporibus suscipit nulla?</p>
        </div>
        <div className="col-md-6 cols">
            <img className="clim" src="../asd.png" alt=""/>
            </div></div>
    
    
    <p className='colio'>_</p>
  

    
  <hr className='hrc' />
</div>

          {/* end of card 3 */}

         {/* card 4 */}
           
<div className="row text-center">
<div className="col-md-6 cols">
            <img className='climo' src="../3e0731a1aebace26ecbebf02a63a6b19.png" alt=""/>
        </div>
        <div className="col-md-6 cols">
            <h2 className="clo">Pay less by subscribing to more platform.</h2>
            <p className="clo">Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis quo, nisi, earum soluta aliquid rerum
                velit
                expedita excepturi fugit obcaecati aspernatur officiis temporibus suscipit nulla?</p>
        </div>
        </div>
     <p className='colio'>_</p>
  

    
  <hr className='hrc' />
    
              {/* end of card 4 */}

            {/* Frequently asked question */}

   <br />
   <h1 className=" bolo clo">Frequently Asked Questions</h1>
        
            {/* toggle 1 */}
      
   <div className='container' >
   <div className="m-4">
    <div className="accordion  " id="myAccordion">
        <div className="accordion-item acco">
            <h2 className="accordion-header" id="headingOne">
                <button type="button" className="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#collapseOne"> What is Russh?</button>									
            </h2>
            <div id="collapseOne" className="accordion-collapse collapse" data-bs-parent="#myAccordion">
                <div className="card-body accob">
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur dolore tenetur culpa mollitia sed ullam nesciunt facilis repellendus ut cupiditate provident perspiciatis iste eaque, officiis quaerat? Magnam, dicta? Debitis, pariatur. <a href="https://www.tutorialrepublic.com/html-tutorial/" target="_blank">Learn more.</a></p>
                </div>
            </div>
        </div>
    </div>    
</div>
</div>

      {/* end of toggle 1 */}

          {/* toggle 2 */}

<div className='container' >
   <div className="m-4">
    <div className="accordion" id="myAccordion">
        <div className="accordion-item acco">
            <h2 className="accordion-header" id="headingTwo">
                <button type="button" className="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#collapsetwo"> How much does Russh cost?</button>									
            </h2>
            <div id="collapsetwo" className="accordion-collapse collapse" data-bs-parent="#myAccordion">
                <div className="card-body accob">
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur dolore tenetur culpa mollitia sed ullam nesciunt facilis repellendus ut cupiditate provident perspiciatis iste eaque, officiis quaerat? Magnam, dicta? Debitis, pariatur. <a href="https://www.tutorialrepublic.com/html-tutorial/" target="_blank">Learn more.</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

        {/* end of toggle 2 */}

        {/* toggle 3 */}

<div className='container' >
   <div className="m-4">
    <div className="accordion" id="myAccordion">
        <div className="accordion-item acco">
            <h2 className="accordion-header" id="headingThree">
                <button type="button" className="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#collapseOne3">How do i cancel my subscription?</button>									
            </h2>
            <div id="collapseOne3" className="accordion-collapse collapse" data-bs-parent="#myAccordion">
                <div className="card-body accob">
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur dolore tenetur culpa mollitia sed ullam nesciunt facilis repellendus ut cupiditate provident perspiciatis iste eaque, officiis quaerat? Magnam, dicta? Debitis, pariatur. <a href="https://www.tutorialrepublic.com/html-tutorial/" target="_blank">Learn more.</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

        {/* end of toggle 3 */}


           {/* toggle 4 */}

<div className='container' >
   <div className="m-4">
    <div className="accordion  " id="myAccordion">
        <div className="accordion-item acco">
            <h2 className="accordion-header" id="headingOne4">
                <button type="button" className="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#collapseOne4">What platforms are available on Russh?</button>									
            </h2>
            <div id="collapseOne4" className="accordion-collapse collapse" data-bs-parent="#myAccordion">
                <div className="card-body accob">
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur dolore tenetur culpa mollitia sed ullam nesciunt facilis repellendus ut cupiditate provident perspiciatis iste eaque, officiis quaerat? Magnam, dicta? Debitis, pariatur. <a href="https://www.tutorialrepublic.com/html-tutorial/" target="_blank">Learn more.</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
         {/* end of toggle 4 */}

          {/* toggle 5 */}

<div className='container' >
   <div className="m-4">
    <div className="accordion  " id="myAccordion">
        <div className="accordion-item acco">
            <h2 className="accordion-header" id="headingfive">
                <button type="button" className="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#collapsefive">How does Russh offer exclusive memberships?</button>									
            </h2>
            <div id="collapsefive" className="accordion-collapse collapse" data-bs-parent="#myAccordion">
                <div className="card-body accob">
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur dolore tenetur culpa mollitia sed ullam nesciunt facilis repellendus ut cupiditate provident perspiciatis iste eaque, officiis quaerat? Magnam, dicta? Debitis, pariatur. <a href="https://www.tutorialrepublic.com/html-tutorial/" target="_blank">Learn more.</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

                 {/* end of toggle 5 */}
                 
                  {/* end of FAQ */}
                   
                   {/* membership email */}

        <p className=" bolon clo">Ready to start? Enter your email to create and begin your membership.</p>
        <div className="member my-5">


        <div className="row">
            <div className="col-xl-6 col-lg-8 col-md-8 col-sm-12  mx-auto">

                <form className="example">
                    <div className="row">
                        <div className="col-12 col-sm-8">


                            <input type="text" placeholder="Email Address" name="search"/>
                        </div>




                        <div className="col-12 col-sm-4 getStartedBTN">


                            <button  type="submit">Get Started</button>

                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>
                    {/* end of membership email */}

                    {/* footer */}
           
          <div className="container-fluid  conBox" >
      
        <footer className="text-center text-lg-start text-white" >
         
            <div className="container p-4 pb-0">
               
                <section className="">
                 
                    <div className="row  footercenter">
                       
                        <div className="col-12 col-sm-3 mt-3">

                            <img src="../bo.png" alt="" className="logo"/>

                         
                            <p>
                                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Minus voluptatem quod quos
                                harum deleniti suscipit corrupti 
                            </p>
                        </div>
                      

                        <hr className="w-100 clearfix d-md-none" />

                      
                        <div className="col-12 col-sm-2 mt-3 colPadding">
                           
                            <ul className="listStyle">
                                <li className="text-white my-3"><i className="fa fa-duotone fa-play iconSize" ></i> Company</li>
                                <li className="text-white my-3"><i className="fa fa-duotone fa-play iconSize" ></i> FAQs</li>
                                <li className="text-white my-3"><i className="fa fa-duotone fa-play iconSize" ></i> Contact Us</li>
                                <li className="text-white my-3"><i className="fa fa-duotone fa-play iconSize" ></i> Blogs</li>

                            </ul>
                        </div>
                      

                        <hr className="w-100 clearfix d-md-none" />

                       
                        <div className="col-12 col-sm-4 mt-3 colPadding" >
                            
                       
                            <ul className="listStyle">
                                <li className="text-white my-3"><i className="fa fa-duotone fa-play iconSize" ></i> Legal</li>
                                <li className="text-white my-3"><i className="fa fa-duotone fa-play iconSize" ></i> Terms & Conditions</li>
                                <li className="text-white my-3"><i className="fa fa-duotone fa-play iconSize" ></i> Privacy Policy</li>
                                <li className="text-white my-3"><i className="fa fa-duotone fa-play iconSize" ></i> About Us</li>

                            </ul>
                       
                        </div>

                      
                        <hr className="w-100 clearfix d-md-none" />

                       
                        <div className="col-12 col-sm-3 mt-3 contactUs" >
                            <h6 className="text-uppercase mb-4 font-weight-bold">Question? Contact</h6>
                        
                            <p><i className="fa fa-envelope mr-3"></i> Send Email</p>
                            <p><i className="fa-solid fa-comment mr-3"></i> Chat With Us</p>
                            <p><i className="fa-solid fa-phone mr-3"></i> Give Us A Call</p>

                            <a className="btn btn-outline-light btn-floating m-1 webIcon text-white"  role="button"><i
                                className="fab fa-facebook-f"></i></a>

                      
                        <a className="btn btn-outline-light btn-floating m-1 webIcon text-white"  role="button"><i
                                className="fab fa-twitter"></i></a>

                        
                        <a className="btn btn-outline-light btn-floating m-1 webIcon text-white"  role="button"><i
                                className="fab fa-youtube"></i></a>

                        <a className="btn btn-outline-light btn-floating m-1 webIcon text-white"  role="button"><i
                                className="fab fa-instagram"></i></a>
                        </div>
                    
                    </div>
                
                </section>
             

                <hr className="my-3"/>

                
                <section className="p-3 pt-0">
                    <div className="row d-flex align-items-center">
                      
                        <div className="col-md-7 col-lg-8 text-center text-md-start">
                            
                            <div className="p-3">
                                © 2022 Copyright:
                                <a className="text-white copyText" href="https://mdbootstrap.com/">Russh Interactive LLC</a>
                            </div>
                           
                        </div>
                     

                       
                        <div className="col-md-5 col-lg-4 ml-lg-0 text-center text-md-end">
                           
                            <a href="#" className="privacy">Privacy Policy|Terms & Conditions</a>
                          
                        </div>
                      
                    </div>
                </section>
                
            </div>
          
        </footer>
       
    </div>
    
                      {/* end of footer */}

          </>
  )
}
